workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      groups:
        - firebase_credentials # Configured securely inside Codemagic project dashboard
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Run Flutter analyzer
        script: |
          flutter analyze
      - name: Run unit tests
        script: |
          flutter test
      - name: Build Android Release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
