// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// SETUP INSTRUCTIONS:
/// 1. Go to https://console.firebase.google.com
/// 2. Create project "creatorlink-app" (or use existing)
/// 3. Add Android app: com.creatorlink.creatorlink
/// 4. Download google-services.json → place in android/app/
/// 5. Run: flutterfire configure
/// 6. Replace ALL placeholder values below with real values from Firebase Console
///    (Project Settings → Your apps → SDK setup and configuration)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// PLACEHOLDER — Replace with real values from Firebase Console
  /// Project Settings → General → Your apps → Google services file
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRX_IqO5tceLaxTwUB2i1il-lypRRdM1o',
    appId: '1:246812613566:android:6a0e80c919b8d9a253b7ef',
    messagingSenderId: '246812613566',
    projectId: 'creatorlink-niraj417',
    storageBucket: 'creatorlink-niraj417.firebasestorage.app',
  );
}
